version: "1.1"
stages:
  - stage:
      - git-checkout:
          alias: git-checkout
          description: 代码仓库克隆
  - stage:
      - custom-script:
          alias: generate-datetime
          description: 运行自定义命令
          image: alpine:3.15.0
          commands:
            - 'echo "action meta: date=$(date ''''+%Y%m%d%H%M%S'''')"'
  - stage:
      - custom-script:
          alias: custom-script
          description: 运行自定义命令
          commands:
            - export image=$REGISTRY_ADDR/erda/flask-demo:$(date '+%Y%m%d%H%M%S')
            - 'echo "image: $image"'
            - docker build ${git-checkout} -t $image && docker push $image
            - 'echo "action meta: image=$image"'
  - stage:
      - release:
          alias: release
          description: 用于打包完成时，向dicehub 提交完整可部署的dice.yml。用户若没在pipeline.yml里定义该action，CI会自动在pipeline.yml里插入该action
          version: "1.0"
          params:
            dice_yml: ${git-checkout}/erda.yml
            image:
              flask-demo: ${custom-script:OUTPUT:image}
  - stage:
      - dice:
          alias: dice
          description: 用于 Erda 平台部署应用服务
          version: "1.0"
          params:
            release_id: ${release:OUTPUT:releaseID}
            time_out: 1800
