version: "1.1"
stages:
  - stage:
      - git-checkout:
          alias: git-checkout
          description: 代码仓库克隆
  - stage:
      - dockerfile:
          alias: dockerfile
          description: 针对自定义 dockerfile 打包，产出可运行镜像
          version: "1.0"
          params:
            path: Dockerfile
            workdir: ${git-checkout}
  - stage:
      - release:
          alias: release
          description: 用于打包完成时，向dicehub 提交完整可部署的dice.yml。用户若没在pipeline.yml里定义该action，CI会自动在pipeline.yml里插入该action
          version: "1.0"
          params:
            dice_yml: ${git-checkout}/erda.yml
            image:
              axum-demo: ${dockerfile:OUTPUT:image}
  - stage:
      - dice:
          alias: dice
          description: 用于 Erda 平台部署应用服务
          version: "1.0"
          params:
            release_id: ${release:OUTPUT:releaseID}
            time_out: 1800
